apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-express-app
spec:
  selector:
    matchLabels: 
      name: s3-express-app
  template:
    metadata:
      labels:
        name: s3-express-app
    spec:  
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: topology.kubernetes.io/zone
                  operator: In
                  values:
                  - ${az} # specify az where bucket lives, note: the code of the availability zone (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html) must be used here (the AZ ID won't work)
      containers:
        - name: app
          image: nginx:latest
          command: ["/bin/sh"]
          args: ["-c", "echo 'Hello from the container!' >> /data/$(date -u).txt; tail -f /dev/null"]
          volumeMounts:
            - name: persistent-storage
              mountPath: /data
          resources:
            limits:
              cpu: 1
              memory: "2Gi"
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: s3-express-claim
