apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-express-pv
spec:
  capacity:
    storage: ${size} # ignored, required
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  mountOptions:
    - allow-delete
    - region ${region}
  csi:
    driver: s3.csi.aws.com # required
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: ${bucket}
